// TRADUZIONI DELLE DESCRIZIONI
const productDescTranslations = {
    1: { EN: "Premium THC vape cartridge", IT: "Cartuccia vape THC premium" },
    2: { EN: "5 pack infused prerolls", IT: "5 preroll infusi" },
    3: { EN: "Sativa dominant vape", IT: "Vape sativa dominante" },
    4: { EN: "Top shelf sativa", IT: "Sativa top quality" },
    5: { EN: "Sweet indica hybrid", IT: "Ibrido indica dolce" },
    6: { EN: "Classic Cookies strain", IT: "Strain Cookies classico" },
    7: { EN: "Premium quality crystal", IT: "Cristallo qualità premium" },
    8: { EN: "Cold extracted hash", IT: "Hash estratto a freddo" },
    9: { EN: "Sweet dessert strain", IT: "Strain dolce da dessert" },
    10: { EN: "Psychedelic mushrooms", IT: "Funghi psichedelici" },
    11: { EN: "Energetic sativa", IT: "Sativa energizzante" },
    12: { EN: "Fruity hybrid", IT: "Ibrido fruttato" },
    13: { EN: "Pure LSD liquid", IT: "LSD liquido puro" },
    14: { EN: "Pure MDMA crystals", IT: "Cristalli MDMA puri" },
    15: { EN: "Covered in kief", IT: "Ricoperto di kief" },
    16: { EN: "Traditional Moroccan", IT: "Marocchino tradizionale" },
    17: { EN: "Classic indica", IT: "Indica classica" },
    18: { EN: "Top quality hash", IT: "Hash top quality" },
    19: { EN: "Bulk pricing available", IT: "Prezzi all'ingrosso" },
    20: { EN: "Fishscale quality", IT: "Qualità fishscale" },
    21: { EN: "Magic mushrooms", IT: "Funghi magici" },
    22: { EN: "Purple indica", IT: "Indica viola" },
    23: { EN: "Colorful hybrid", IT: "Ibrido colorato" },
    24: { EN: "Premium disposable", IT: "Vape usa e getta premium" },
    25: { EN: "Sweet candy strain", IT: "Strain caramella dolce" },
    26: { EN: "Icy hybrid", IT: "Ibrido ghiacciato" },
    27: { EN: "Classic sativa", IT: "Sativa classica" },
    28: { EN: "7 pack classic joints", IT: "7 joints classici" },
    29: { EN: "Gummies 40mg THC", IT: "Gummies 40mg THC" },
    30: { EN: "Gummies 60mg THC", IT: "Gummies 60mg THC" },
    31: { EN: "Balanced hybrid", IT: "Ibrido bilanciato" },
    32: { EN: "Fruit flavored vape", IT: "Vape al frutto" },
};

// CATALOGO PRODOTTI - I TUOI 32 PRODOTTI ESATTI
const products = [
    { id: 1, name: "Amnesia Vape", category: "vape", price: 70, image: "https://files.catbox.moe/k6utct.jpg", desc: "Premium THC vape cartridge" },
    { id: 2, name: "Baby Jeeter Prerolls", category: "prerolls", price: 30, image: "https://files.catbox.moe/uzsqh3.jpg", desc: "5 pack infused prerolls" },
    { id: 3, name: "Blue Dream Vape", category: "vape", price: 70, image: "https://files.catbox.moe/e42bu5.jpg", desc: "Sativa dominant vape" },
    { id: 4, name: "Blue Dream", category: "weed", price: 12, image: "https://files.catbox.moe/l3rb72.jpg", desc: "Top shelf sativa" },
    { id: 5, name: "Bubblegum Gusher", category: "weed", price: 12, image: "https://files.catbox.moe/q1vuzm.jpg", desc: "Sweet indica hybrid" },
    { id: 6, name: "Cookies", category: "weed", price: 12, image: "https://files.catbox.moe/9cm291.jpg", desc: "Classic Cookies strain" },
    { id: 7, name: "Crystal Meth Special", category: "special", price: 60, image: "https://files.catbox.moe/sg5khm.jpg", desc: "Premium quality crystal" },
    { id: 8, name: "Frozen Sift Hash", category: "hash", price: 15, image: "https://files.catbox.moe/dwnep1.jpg", desc: "Cold extracted hash" },
    { id: 9, name: "Gelato", category: "weed", price: 12, image: "https://files.catbox.moe/iuulm3.jpg", desc: "Sweet dessert strain" },
    { id: 10, name: "Golden Teacher", category: "mushrooms", price: 40, image: "https://files.catbox.moe/4bcbhp.jpg", desc: "Psychedelic mushrooms" },
    { id: 11, name: "Green Crack", category: "weed", price: 12, image: "https://files.catbox.moe/dpq2lc.jpg", desc: "Energetic sativa" },
    { id: 12, name: "Lemon Cherry", category: "weed", price: 12, image: "https://files.catbox.moe/nkf4c3.jpg", desc: "Fruity hybrid" },
    { id: 13, name: "LSD Liquid Special", category: "special", price: 50, image: "https://files.catbox.moe/upcbag.jpg", desc: "Pure LSD liquid" },
    { id: 14, name: "MDMA Special", category: "special", price: 65, image: "https://files.catbox.moe/6xqi64.jpg", desc: "Pure MDMA crystals" },
    { id: 15, name: "Moonrock", category: "weed", price: 20, image: "https://files.catbox.moe/i4nqr1.jpg", desc: "Covered in kief" },
    { id: 16, name: "Moroccan Dry Hash", category: "hash", price: 8, image: "https://files.catbox.moe/kbbn9j.jpg", desc: "Traditional Moroccan" },
    { id: 17, name: "Northern Lights", category: "weed", price: 12, image: "https://files.catbox.moe/jnv4ei.jpg", desc: "Classic indica" },
    { id: 18, name: "Premium Hash", category: "hash", price: 12, image: "https://files.catbox.moe/wlsxrg.jpg", desc: "Top quality hash" },
    { id: 19, name: "Premium Wholesale", category: "weed", price: 7.5, image: "https://files.catbox.moe/1ah9ve.jpg", desc: "Bulk pricing available" },
    { id: 20, name: "Pure Cocaine", category: "special", price: 120, image: "https://files.catbox.moe/vghr7c.jpg", desc: "Fishscale quality" },
    { id: 21, name: "Purple Mystic", category: "mushrooms", price: 45, image: "https://files.catbox.moe/qvzz3u.jpg", desc: "Magic mushrooms" },
    { id: 22, name: "Purple Platinum", category: "weed", price: 12, image: "https://files.catbox.moe/p393wj.jpg", desc: "Purple indica" },
    { id: 23, name: "Rainbow Zaza", category: "weed", price: 12, image: "https://files.catbox.moe/pbjgn1.jpg", desc: "Colorful hybrid" },
    { id: 24, name: "Runtz Vape", category: "vape", price: 70, image: "https://files.catbox.moe/pjj7h1.jpg", desc: "Premium disposable" },
    { id: 25, name: "Runtz", category: "weed", price: 12, image: "https://files.catbox.moe/xxeqh7.jpg", desc: "Sweet candy strain" },
    { id: 26, name: "Snowcone", category: "weed", price: 12, image: "https://files.catbox.moe/3m3tdq.jpg", desc: "Icy hybrid" },
    { id: 27, name: "Sour Diesel", category: "weed", price: 12, image: "https://files.catbox.moe/pk12h0.jpg", desc: "Classic sativa" },
    { id: 28, name: "Standard Prerolls", category: "prerolls", price: 15, image: "https://files.catbox.moe/9tu5hx.jpg", desc: "7 pack classic joints" },
    { id: 29, name: "THC Edibles 40mg", category: "edibles", price: 40, image: "https://files.catbox.moe/wlkvg0.jpg", desc: "Gummies 40mg THC" },
    { id: 30, name: "THC Edibles 60mg", category: "edibles", price: 60, image: "https://files.catbox.moe/8ymlq9.jpg", desc: "Gummies 60mg THC" },
    { id: 31, name: "White Widow", category: "weed", price: 12, image: "https://files.catbox.moe/dux0y2.jpg", desc: "Balanced hybrid" },
    { id: 32, name: "Zkittlez Vape", category: "vape", price: 70, image: "https://files.catbox.moe/chrkoa.jpg", desc: "Fruit flavored vape" }
];
